anomaly_detector:
  ros__parameters:
    cluster_tolerance: 0.6
    min_cluster_size: 6
    max_cluster_size: 100000
    min_obstacle_height: 0.15
    max_obstacle_length: 5.0
    max_obstacle_width: 2.7
    density_coefficient: 900.0

gauge_filter:
  ros__parameters:
    min_x: 2.0
    max_x: 300.0
    min_y: -1.5
    max_y: 1.5
    min_z: -1.1
    max_z: 3.0

preprocessor:
  ros__parameters:
    min_z_safety: -1.3
    max_z_safety: 1.3
